---
# File: tasks.yml
# Part: Mongodb
#
# Description:
# - Install MongoDB from 10gen packages
#
# Parameters:
#
# Dependencies ([part:]type:filename):
#
# OS familly: Ubuntu >= 12.04

- name: MongoDB | Update apt caches.
  command: apt-get update

- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

- name: MongoDB | Add 10Gen repository
  shell: 
    echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
    creates=/etc/apt/sources.list.d/10gen.list

- name: MongoDB | Install latest MongoDB release 
  apt: pkg=mongodb-10gen state=present update_cache=yes
  
- name: MongoDB | Create the mongod user
  user: name=mongod comment="MongoD user"

- name: Create the data directory for the namenode metadata
  file: path={{ mongodb_data_dir_prefix }} owner=mongod group=mongod state=directory
  
- name: Create the journal directory for the namenode metadata
  file: path={{ mongodb_journal_dir }} owner=mongod group=mongod state=directory
  
- name: Create the log directory for the namenode metadata
  file: path={{ mongodb_log_dir }} owner=mongod group=mongod state=directory    

- name: MongoDB | Push default configuration template
  template:
    src=$repository_basedir/mongodb/templates/mongodb.conf.j2
    dest=/etc/mongodb.conf
    owner=mongod group=mongod mode=0644
  notify: mongodb-restart

# Insure service is running.
- name: MongoDB | Insure deamon is running correctly
  service: name=mongodb state=started

