---
# File: mongodb-install.yml
# Part: Mongodb
#

- hosts: rev_aws_us_west_ca_ubuntu
  user: ubuntu
  sudo: True
  
  vars:
    repository_basedir: ..

  tasks:
    - include: $repository_basedir/mongodb/tasks/setup.yml
