---
# File: tasks.yml
# Part: Mongodb
#
# Description:
# - Install MongoDB from 10gen packages
#
# Parameters:
#
# Dependencies ([part:]type:filename):
#

- name: MongoDB | Update apt caches.
  command: apt-get update

- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

- name: MongoDB | Add 10Gen repository
  shell: 
    echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
    creates=/etc/apt/sources.list.d/10gen.list

- name: MongoDB | Install latest MongoDB release 
  apt: pkg=mongodb-10gen state=present update_cache=yes
  
- name: MongoDB | Create the mongod user
  user: name=mongod comment="MongoD user"
  
- name: Create the data directory for the namenode metadata
  file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory
    
# TODO: Setup soft/hard file descriptor limits

# TODO: Setup NTP    

# Insure service is running.
- name: MongoDB | Insure deamon is running correctly
  service: name=mongodb state=started